# .prettierrc
arrowParens: avoid
bracketSpacing: true
printWidth: 120
singleQuote: true
tabWidth: 4
trailingComma: none
overrides:
    - files: '*.html'
      options:
          parser: angular
    - files: '*.json'
      options:
          tabWidth: 2
